#!/usr/bin/env perl

use strict;

# check by default
my @mode;

my @files = grep {
    $_ ne '--fix'or not (@mode = ('--fix'));
} @ARGV;

@files = qw/ src / unless @files;

exec 'eslint', @mode, @files;
